import type { Metadata } from 'next'
import { Geist, Geist_Mono } from 'next/font/google'
import '../../config/styles/globals.css'
import Providers from '@/shared/providers/query-provider'
import { ThemeProvider } from '@/shared/providers/theme-provider'
import { Navbar } from '@/widgets/navbar'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Todo App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <Providers>
            <Navbar />
            {children}
            </Providers>
        </ThemeProvider>
      </body>
    </html>
  )
}
